# Generated by Django 2.1 on 2018-08-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180824_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='f_hard',
            field=models.BooleanField(default=False),
        ),
    ]
